"""add invoice imported by columns

Revision ID: 246c67c1d45e
Revises: 7129c5082ac9
Create Date: 2026-09-06 13:58:11.152569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246c67c1d45e'
down_revision: Union[str, Sequence[str], None] = '7129c5082ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('imported_by_kassennummer', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('imported_by_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'imported_by_name')
    op.drop_column('invoices', 'imported_by_kassennummer')
    # ### end Alembic commands ###
