"""add users table

Revision ID: 7129c5082ac9
Revises: 5ce94c6a96e3
Create Date: 2026-09-06 13:23:23.599969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7129c5082ac9'
down_revision: Union[str, Sequence[str], None] = '5ce94c6a96e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kassennummer', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(role = 'chef' AND password_hash IS NOT NULL) OR (role = 'mitarbeiter' AND password_hash IS NULL)", name='ck_users_chef_has_password'),
    sa.CheckConstraint("role IN ('mitarbeiter', 'chef')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_kassennummer'), 'users', ['kassennummer'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_kassennummer'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
